### ISSUE TITLE
FireFox

### ISSUE THREAD

**Issue by gdpl** [BrianAdams/openrov-mjpeg-video-webcomponent#1]
Shows only first jpeg from stream (HIKIVISION DS-2CD2032-I camera).

**Comment by AnthonyDewhirst** [comment]
Just tried to use bower to pull this and it said couldn't be found?
bower install mjpeg-video-webcomponent
bower                        ENOTFOUND Package mjpeg-video-webcomponent not found

**Comment by BrianAdams** [comment]
@gdpl thanks for the report. Will hopefully get a chance to look at this over the weekend.

**Comment by BrianAdams** [comment]
Assuming the instructions fixed this...
